// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhriUxHfsbaKShEHuKzuqbJMFqyThJW5g',
    appId: '1:910481201497:web:479b102fb367afd5b09448',
    messagingSenderId: '910481201497',
    projectId: 'grocerymanager-a4cdb',
    authDomain: 'grocerymanager-a4cdb.firebaseapp.com',
    storageBucket: 'grocerymanager-a4cdb.appspot.com',
    measurementId: 'G-1Q3YN20T5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK73aj33ijlr1M9PiGrPX82Q98hajvB4g',
    appId: '1:910481201497:android:7c710ed96eba1ec8b09448',
    messagingSenderId: '910481201497',
    projectId: 'grocerymanager-a4cdb',
    storageBucket: 'grocerymanager-a4cdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDah918XXfrwqfpnmkfY_3PRpU6cQnd7N8',
    appId: '1:910481201497:ios:ce31929be1b7f4d9b09448',
    messagingSenderId: '910481201497',
    projectId: 'grocerymanager-a4cdb',
    storageBucket: 'grocerymanager-a4cdb.appspot.com',
    iosClientId: '910481201497-2nfev9llnif1tca26imb477169jsr7vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDah918XXfrwqfpnmkfY_3PRpU6cQnd7N8',
    appId: '1:910481201497:ios:ce31929be1b7f4d9b09448',
    messagingSenderId: '910481201497',
    projectId: 'grocerymanager-a4cdb',
    storageBucket: 'grocerymanager-a4cdb.appspot.com',
    iosClientId: '910481201497-2nfev9llnif1tca26imb477169jsr7vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryManager',
  );
}
